### ISSUE TITLE
Can't start game on Manjaro

### ISSUE THREAD

**Issue by olk90** [taiidani/hwrc-proton-launcher#1]
Hi,

first of all a big thanks for this application, I was always missing a UI to select the version on the fly. 

But I encountered an issue when launching Homeworld Remastered. There I receive the following error:

```
FATA[0014] Unable to change directory to game path: chdir ~/.local/share/Steam/steamapps/common/Homeworld/HomeworldRM/bin/Release: no such file or directory
```

This seems related to the `Bin` directory on my machine starting with a capital B.

Is there any general fix or should I just change `steam.go` on my local installation?

BR

**Comment by taiidani** [comment]
Hi @olk90. Thanks for the report! I won't be able to get to this for a few days, but in the meantime if you're comfortable with the Go toolchain can you try capitalizing the B in the `steam.go` file and report if it fixes the bug for you?

If so I (or you if you'd like) will see about adding logic to cleanly try both path formats.

**Comment by olk90** [comment]
With a capital B in the path the game will launch without issues. I'll implement a general solution in the next days ... I'm kinda busy but I'll find the time.

**Edit:** s. https://github.com/taiidani/hwrc-proton-launcher/pull/2
